"""empty message

Revision ID: 53e70afc32d8
Revises: 
Create Date: 2017-04-23 11:54:08.183834

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53e70afc32d8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('invitecode')
    op.create_table('InviteCode',
    sa.Column('invite_code_id', sa.Integer(), nullable=False),
    sa.Column('invite_code', sa.String(length=33), nullable=True),
    sa.PrimaryKeyConstraint('invite_code_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_ibfk_1', 'movies', 'categories', ['movie_category'], ['category_id'])
    op.create_table('invitecode',
    sa.Column('invite_code_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('invite_code', mysql.VARCHAR(length=33), nullable=True),
    sa.PrimaryKeyConstraint('invite_code_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('categories',
    sa.Column('category_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('category_name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('category_url', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('category_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('score',
    sa.Column('score_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('score_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('score_percent', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('User_email', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['User_email'], ['users.email'], name='Score_ibfk_1'),
    sa.PrimaryKeyConstraint('score_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('word_bank',
    sa.Column('wb_collection', mysql.TEXT(), nullable=True),
    sa.Column('wb_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('user_wb', mysql.VARCHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_wb'], ['users.email'], name='Word_Bank_ibfk_1'),
    sa.PrimaryKeyConstraint('wb_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('Word_Bank')
    op.drop_table('Score')
    op.drop_table('InviteCode')
    op.drop_table('Categories')
    # ### end Alembic commands ###
